language: python
python:
  - "3.5"
env:
  - DJANGO_VERSION=1.9.1
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: py.test test_simple.py