# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161008_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Локация'),
        ),
    ]
